algoritmo "Exemplos"
// Função :
// Autor :
// Data : 01/04/2021
// Seção de Declarações 
var
A: Inteiro
B: Real
C: Real
D: Real
F: Real
G: Real
inicio
// Seção de Comandos 
 A <- Abs(-50)
 Escreval(A)
 B <- Exp (9 , 5)
 Escreval(B)
 C <- RaizQ (90)
 Escreval(C)
 D <- Int(RaizQ(90))
 Escreval(D)
 F <- GraupRad(90)
 Escreval(F)
 G <- Sen(GraupRad(90))
 Escreval(G)
 
fimalgoritmo
