algoritmo "Conta Negativos"
// Função :
// Autor :
// Data : 06/04/2021
// Seção de Declarações 
var
    N,C, TotN:Inteiro
inicio
// Seção de Comandos
    C<-1
    TotN <- 0
     Repita
        Escreva("Digite um número:")
        Leia(N)
        Se (N<0) entao
           TotN <- TotN + 1
        FimSe
        C <- C + 1
     Ate (C > 5)
    EscrevaL("Foram digitados ", TotN, " valores negativos. ")
      
fimalgoritmo
