algoritmo "Meu nome e números"
// Função :
// Autor :
// Data : 01/04/2021
// Seção de Declarações 
var
 Nome: caractere
 N1 , N2 , S: inteiro
inicio
// Seção de Comandos 
Escreva("Digite seu nome: ")
Leia(Nome)
Escreval("Muito prazer em te conhecer " , Nome)
Escreva("Informe um número: ")
Leia(N1)
Escreva("Informe outro número: ")
Leia(N2)
S <- N1 + N2
Escreva("A respota da soma entre ",N1, " e ", N2 , " é igual a " , S)
fimalgoritmo

