algoritmo "Somador2"
// Função :
// Autor :
// Data : 06/04/2021
// Seção de Declarações 
var
   N,S:Inteiro
   resp:caractere
inicio
// Seção de Comandos 
      S <- 0
      Repita
         Escreva("Digite o valor :")
         Leia(N)
         S <- S+N)
         Escreva("Você quer continuar? [S/N]")
         Leia(resp)
      Ate (resp = "N")
      EscrevaL("A soma de todos os valores digitados é:",S)
fimalgoritmo
